#!/bin/bash

flash_iptables (){

	iptables -F
	for i in $mas_curr_ip $cl_curr_ip
	do
	ssh $i "iptables -F"
	done
	echo "flash iptables done"
}




restart_network (){

	systemctl restart network
	echo "network restart done"
}


start_ypbind (){

	systemctl start ypbind
	systemctl enable ypbind
	echo "ypbind start done"
}


start_ypserv (){

	systemctl start ypserv
	systemctl enable ypserv
	echo "ypserv start done"
}

start_rpcbind (){

	systemctl start rpcbind
	systemctl enable rpcbind
	echo "rpcbind start done"
}

